<a href="https://colab.research.google.com/github/Ganeshkumar-1358/batch-20_1358/blob/main/LAB_2_1358.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
l=[10,"ganesh",33.3]
for i in l:
  print(type(i),i)

<class 'int'> 10
<class 'str'> ganesh
<class 'float'> 33.3


In [ ]:
l=[10,20,30,40]
print(l)
if 20 in l:
  print("found")
else:
  print("not found")
l.append(50)
print(l)
l.remove(20)
print(l)
l.insert(1,20)
print(l)
l.pop()
print(l)
l.reverse()
print(l)
l.sort()
print(l)
print(sum(l))
print(min(l))
print(max(l))

[10, 20, 30, 40]
found
[10, 20, 30, 40, 50]
[10, 30, 40, 50]
[10, 20, 30, 40, 50]
[10, 20, 30, 40]
[40, 30, 20, 10]
[10, 20, 30, 40]
100
10
40


In [ ]:
std=[[10,20,],[30,40],[50,60],[70,80],[90,100]]
for i in std:
  print(i)
#tuple
t=(1,2.2,"ganesh")
for i in t:
  print(type(i),i)
tuple=(1,2,3,4,5,6,2,3,4,5,2,3,4,4,5)
print(tuple)
print(tuple.count(5))
print(tuple.index(5))
if 6 in t:
  print("found")
else:
  print("not found")

[10, 20]
[30, 40]
[50, 60]
[70, 80]
[90, 100]
<class 'int'> 1
<class 'float'> 2.2
<class 'str'> ganesh
(1, 2, 3, 4, 5, 6, 2, 3, 4, 5, 2, 3, 4, 4, 5)
3
4
not found


In [ ]:
l=[1,2,3,4,5]
mytuple=tuple(l)
print(my_tuple)

NameError: name 'my_tuple' is not defined

In [ ]:
student={"101":{"name":"ganesh","id":"1358"},"420":{"name":"naga","id":"1361"}}
print(student.keys())
print(student.values())
print(student.items())

dict_keys(['101', '420'])
dict_values([{'name': 'ganesh', 'id': '1358'}, {'name': 'naga', 'id': '1361'}])
dict_items([('101', {'name': 'ganesh', 'id': '1358'}), ('420', {'name': 'naga', 'id': '1361'})])


In [ ]:
l=[[10,20],[30,40],[50,60]]
for i in l:
  print(*i)

10 20
30 40
50 60


In [ ]:
import numpy as np
# Step 1: Create a 2D NumPy array
# Rows: Students, Columns: Subjects (e.g., Math, Science, English)
marks = np.array([
    [78, 85, 90],
    [92, 88, 95],
    [65, 70, 72],
    [88, 91, 85],
    [56, 60, 62],
    [81, 79, 83]
])

print("Student Marks (Rows=Students, Columns=Subjects):\n", marks)

# Step 2: Calculate average, min, and max
avg_marks = np.mean(marks, axis=1)  # Average per student
min_marks = np.min(marks, axis=1)
max_marks = np.max(marks, axis=1)

print("\nAverage Marks of Each Student:", avg_marks)
print("Minimum Marks of Each Student:", min_marks)
print("Maximum Marks of Each Student:", max_marks)

# Step 3: Slicing - Get marks of 2nd and 4th students (index 1 and 3)
selected_students = marks[[1, 3], :]
print("\nMarks of 2nd and 4th Students:\n", selected_students)

# Step 4: Boolean indexing - Find students with any subject marks > 80
above_80 = marks[np.any(marks > 80, axis=1)]
print("\nStudents scoring above 80 in any subject:\n", above_80)

# Step 5: Reshape the array to subject-wise (3 subjects, many students)
reshaped = marks.T  # Transpose to make rows = subjects
print("\nReshaped Array (Subjects as Rows):\n", reshaped)

# Step 6: Comment / Analysis
print("\n--- Analysis ---")
print("1. Student 2 and 4 performed consistently well across subjects.")
print("2. Students 3 and 5 need improvement in all subjects.")
print("3. Science and English have slightly higher average scores than Math.")


Student Marks (Rows=Students, Columns=Subjects):
 [[78 85 90]
 [92 88 95]
 [65 70 72]
 [88 91 85]
 [56 60 62]
 [81 79 83]]

Average Marks of Each Student: [84.33333333 91.66666667 69.         88.         59.33333333 81.        ]
Minimum Marks of Each Student: [78 88 65 85 56 79]
Maximum Marks of Each Student: [90 95 72 91 62 83]

Marks of 2nd and 4th Students:
 [[92 88 95]
 [88 91 85]]

Students scoring above 80 in any subject:
 [[78 85 90]
 [92 88 95]
 [88 91 85]
 [81 79 83]]

Reshaped Array (Subjects as Rows):
 [[78 92 65 88 56 81]
 [85 88 70 91 60 79]
 [90 95 72 85 62 83]]

--- Analysis ---
1. Student 2 and 4 performed consistently well across subjects.
2. Students 3 and 5 need improvement in all subjects.
3. Science and English have slightly higher average scores than Math.
