<a href="https://colab.research.google.com/github/Ganeshkumar-1358/batch-20_1358/blob/main/python_LAB_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
fp=open("new.txt","w")
fp.write("helo, world!\n")
fp.write("this is file handling in python.\n")
fp.write("SRU\n")
fp.close()
fp=open("new.txt","r")
str=fp.read()
print(str)
fp.close()

helo, world!
this is file handling in python.
SRU



In [5]:
fp=open("new.txt","r")
line1=fp.readline()
print(line1)
line2=fp.readline()
print(line2)
line3=fp.readline()
print(line3)
fp.close()

helo, world!

this is file handling in python.

SRU



In [7]:
fp=open("new.txt","r")
lines=fp.readlines()
print(lines)
fp.close()

['helo, world!\n', 'this is file handling in python.\n', 'SRU\n']


In [15]:
fp=open("new.txt","a")
fp.write("HELLO SRU \n")
fp=open("new.txt","r")
str=fp.read()
print(str)
fp.close()


helo, world!
this is file handling in python.
SRU
hlo SRU 
hlo SRU 
HELLO SRU 



In [18]:
import csv
with open("data.csv","w",newline='') as fp:
  wr=csv.writer(fp)
  wr.writerows([["Name","Age","course"],["ganesh","21","CSE"],["naga naidu",20,"EEE"]])


In [20]:
with open("data.csv","r") as file:
  re=csv.reader(file)
  for row in re:
    print(row)

['Name', 'Age', 'course']
['ganesh', '21', 'CSE']
['naga naidu', '20', 'EEE']


In [32]:
import numpy as np
#1d array
arr1=np.array([1,2,3,4])
print("1D:",arr1)
#2D array
arr2=np.array([[1,2,3,4],[5,6,7,8]])
print("2D:",arr2)
zeros_arr=np.zeros((3,3))
print("Zeros Array: \n",zeros_arr)
#ones Array
ones_arr=np.ones((3,3))
print(ones_arr)
#range
range_arr=np.arange(1,10,2)
print(range_arr)
#random
rand_arr=np.random.rand(3,3)
print(rand_arr)

1D: [1 2 3 4]
2D: [[1 2 3 4]
 [5 6 7 8]]
Zeros Array: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[1 3 5 7 9]
[[0.76896594 0.03718598 0.03697619]
 [0.88946707 0.42680691 0.03452568]
 [0.17407367 0.14463654 0.74961826]]


In [33]:
#Array Attributes
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)
print(arr.itemsize)

(2, 4)
8
int64
2
8


In [34]:
#1D array
arr=np.array([1,2,3,4,5,6,7,8])
print(arr[0])
print(arr[-1])
print(arr[1:4])
print(arr[::2])

1
8
[2 3 4]
[1 3 5 7]


In [35]:
#2D Array
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr[0,1])
print(arr[1,:])
print(arr[:1])

2
[5 6 7 8]
[[1 2 3 4]]


In [37]:
#Array operations
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**b)

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[    1    64  2187 65536]


In [43]:
#Aggregate Function
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.sum())
print(arr.min())
print(arr.max())
print(arr.mean())
print(arr.std())
print(np.std(arr,axis=0))

36
1
8
4.5
2.29128784747792
[2. 2. 2. 2.]


In [45]:
#broadcasting
a=np.array([1,2,3])
b=5
print(a+b)
c=np.array([[1],[2],[3]])
d=np.array([4,5,6])
print(c+d)

[6 7 8]
[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [46]:
import numpy as np
marks=np.array([[85,90,88],[78,81,85],[92,89,95]])
print("avg mks per std:",np.mean(marks,axis=1))
print("avg mks per sub:",np.mean(marks,axis=0))
print("highest marks in esch subjects:",np.max(marks,axis=0))
print("lowest marks in esch subjects:",np.min(marks,axis=0))

avg mks per std: [87.66666667 81.33333333 92.        ]
avg mks per sub: [85.         86.66666667 89.33333333]
highest marks in esch subjects: [92 90 95]
lowest marks in esch subjects: [78 81 85]
